#!/bin/bash

# Check if the user is root
if [ $(id -u) -ne 0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

# Get the username and password from the user
read -p "Enter username: " username
read -sp "Enter password: " password

# Add the user with the given username and password
useradd -m $username
echo "$username:$password" | chpasswd
