#!/bin/bash

# Check if the user is root
if [ $(id -u) -ne 0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

# Get the username from the user
read -p "Enter username you want to deleting : " username

# Delete the user with the given username
userdel -r $username
echo "$username deleted"
