#!/bin/bash

# Check if the user is root
if [ $(id -u) -ne 0 ]; then
    echo "You must be root to run this script."
    exit 1
fi
echo "enter group name"
read group
# Add a new group
groupdel $group
echo "$group group deleted"
