#!/bin/bash

# Check if the user is root
if [ $(id -u) -ne 0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

# Get the username from the user
read -p "Enter username: " username

# Disable the user with the given username
usermod --expiredate 1 $username
echo "$username disabled"
